#!/c/Users/94233/AppData/Local/Python/bin/python.exe -X utf8
"""
五行英语牌 — 完整词表生成器 v2.0
生成 vocabulary.json（约1000词，含翻译+五行分配+例句）
"""
import json, random, itertools

random.seed(42)

with open('vocabulary.json', encoding='utf-8') as f:
    OLD = json.load(f)
OLD_MAP = {w['word'].lower(): w for w in OLD['words']}

ELEMENTS = ['木','火','土','金','水']
ELEM_CYCLE = itertools.cycle(ELEMENTS)

ELEM_MANUAL = {
    '水':'水','rain':'水','river':'水','sea':'水','ocean':'水','lake':'水',
    'swim':'水','fish':'水','ice':'水','snow':'水','cold':'水','drink':'水',
    'blue':'水','milk':'水','juice':'水','soup':'水','tea':'水','cry':'水',
    'sun':'火','sunny':'火','hot':'火','warm':'火','red':'火','orange':'火',
    'pink':'火','lamp':'火','temperature':'火','tree':'木','flower':'木',
    'green':'木','forest':'木','garden':'木','moon':'金','star':'金','white':'金',
    'key':'金','stone':'土','mountain':'土','brown':'土','earth':'土',
}

def assign_element(word):
    wl = word.lower()
    if wl in ELEM_MANUAL:
        return ELEM_MANUAL[wl]
    return next(ELEM_CYCLE)

# ============================================================
# 旧分类 → 新主题 映射
# ============================================================
CAT_MAP = {
    '动物':'动物','水果':'水果·食物','食物饮品':'水果·食物','颜色':'颜色·形状',
    '形状':'颜色·形状','数词':'数字','身体':'身体','家庭':'家庭·称呼',
    '交通工具':'交通工具','玩具与物品':'玩具·学校','学校用品':'玩具·学校',
    '衣物':'衣物','动词':'动作·动词','形容词':'描述·形容词',
    '代词':'日常用语·代词·介词','冠词/限定词':'日常用语·代词·介词',
    '介词':'日常用语·代词·介词','连词':'日常用语·代词·介词',
    '副词':'日常用语·代词·介词','感叹词':'日常用语·代词·介词',
    '时间':'时间·星期','天气与自然':'季节·天气·自然',
    '房屋与房间':'房屋·家具','其他':'其他补充',
}

TIER_MAP = {
    '动物':'beginner','水果·食物':'beginner','颜色·形状':'beginner',
    '数字':'beginner','身体':'beginner','家庭·称呼':'beginner',
    '交通工具':'beginner','玩具·学校':'beginner','衣物':'beginner',
    '动作·动词':'beginner','描述·形容词':'beginner','日常用语·代词·介词':'beginner',
    '食物·生活':'intermediate','房屋·家具':'intermediate','场所·建筑':'intermediate',
    '季节·天气·自然':'intermediate','时间·星期':'intermediate','身体·健康':'intermediate',
    '动词Ⅱ':'intermediate','形容词Ⅱ':'intermediate','运动·爱好':'intermediate',
    '代词·限定词Ⅱ':'intermediate','介词·连词Ⅱ':'intermediate','疑问·副词':'intermediate',
    '数词·量词':'intermediate','其他补充':'intermediate',
    '抽象概念':'intermediate','人与社会':'intermediate','自然·环境':'intermediate',
    '学校·学习':'intermediate','动词Ⅲ':'intermediate','形容词Ⅲ':'intermediate',
    '时间·频率副词':'intermediate','节日·文化':'intermediate','科技·媒体':'intermediate',
    '连词·介词·情态':'intermediate',
}

def make_sentence(word, cn, pos):
    w = word.lower()
    if w in OLD_MAP and OLD_MAP[w].get('sentence'):
        return OLD_MAP[w]['sentence']

    concrete_nouns = ['knee','shoulder','plate','bowl','cup','fork','spoon','knife',
        'wall','floor','mirror','shelf','drawer','closet','computer','screen',
        'keyboard','mouse','lantern','robot','crayon','boot','taxi','headache',
        'toothache','bathroom','bedroom','library','hospital','supermarket',
        'restaurant','museum','bridge','farm','village','building','gym','pool',
        'monday','tuesday','wednesday','thursday','friday','saturday','sunday',
        'calendar','clock','drum','guitar','piano','violin','doll','ball','block',
        'kite','balloon']
    if pos == 'noun' and w.lower() in concrete_nouns:
        return f'I see a {w.lower()}.'
    elif pos == 'noun':
        return f'This is {w.lower()}.'
    elif pos == 'verb':
        es_words = {'wash','brush','fix','mix','pass','push','reach','teach','dress','watch','catch','touch'}
        ie_words = {'fly','try','cry','carry','hurry','study','worry'}
        if w in es_words:
            return f'He {w}es every day.'
        elif w in ie_words:
            return f'She {w[:-1]}ies well.'
        else:
            return f'I can {w}.'
    elif pos == 'adj':
        return f'I feel {w}.'
    elif pos == 'adv':
        return f'Do it {w}.'
    elif pos == 'pron':
        return f'{word.capitalize()} is here.'
    elif pos == 'prep':
        return f'Go {w} the door.'
    elif pos == 'conj':
        return f'Come {w} you can.'
    elif pos == 'art':
        return f'{word.capitalize()} one is good.'
    elif pos == 'num':
        return f'{word.capitalize()} is a number.'
    elif pos == 'interj':
        return f'{word.capitalize()}!'
    elif pos == 'aux':
        return f'I {w} go.'
    return f'This is {w}.'

# ============================================================
# 新词定义（词汇表中不存在才添加）
# ============================================================
NEW_WORDS = [
    # 1-2年级缺词
    ('knee','膝盖','noun','身体'),
    ('shoulder','肩膀','noun','身体'),
    ('uncle','叔叔/舅舅','noun','家庭·称呼'),
    ('aunt','阿姨/姑姑','noun','家庭·称呼'),
    ('cousin','堂/表兄弟姐妹','noun','家庭·称呼'),
    ('taxi','出租车','noun','交通工具'),
    ('crayon','蜡笔','noun','玩具·学校'),
    ('paint','颜料','noun','玩具·学校'),
    ('boot','靴子','noun','衣物'),
    ('fly','飞','verb','动作·动词'),
    ('clap','拍手','verb','动作·动词'),
    ('wave','挥手','verb','动作·动词'),
    ('please','请','adv','日常用语·代词·介词'),
    ('sorry','对不起','adj','日常用语·代词·介词'),
    ('thanks','谢谢','interj','日常用语·代词·介词'),
    ('welcome','欢迎','interj','日常用语·代词·介词'),
    # 3-4年级
    ('breakfast','早餐','noun','食物·生活'),
    ('lunch','午餐','noun','食物·生活'),
    ('dinner','晚餐','noun','食物·生活'),
    ('plate','盘子','noun','食物·生活'),
    ('bowl','碗','noun','食物·生活'),
    ('cup','杯子','noun','食物·生活'),
    ('fork','叉子','noun','食物·生活'),
    ('spoon','勺子','noun','食物·生活'),
    ('knife','刀','noun','食物·生活'),
    ('delicious','美味的','adj','食物·生活'),
    ('wall','墙','noun','房屋·家具'),
    ('floor','地板','noun','房屋·家具'),
    ('stairs','楼梯','noun','房屋·家具'),
    ('mirror','镜子','noun','房屋·家具'),
    ('shelf','架子','noun','房屋·家具'),
    ('drawer','抽屉','noun','房屋·家具'),
    ('closet','壁橱','noun','房屋·家具'),
    ('bathroom','浴室','noun','房屋·家具'),
    ('bedroom','卧室','noun','房屋·家具'),
    ('library','图书馆','noun','场所·建筑'),
    ('hospital','医院','noun','场所·建筑'),
    ('supermarket','超市','noun','场所·建筑'),
    ('restaurant','餐厅','noun','场所·建筑'),
    ('museum','博物馆','noun','场所·建筑'),
    ('bridge','桥','noun','场所·建筑'),
    ('farm','农场','noun','场所·建筑'),
    ('village','村庄','noun','场所·建筑'),
    ('building','建筑物','noun','场所·建筑'),
    ('gym','体育馆','noun','场所·建筑'),
    ('pool','游泳池','noun','场所·建筑'),
    ('spring','春天','noun','季节·天气·自然'),
    ('summer','夏天','noun','季节·天气·自然'),
    ('autumn','秋天','noun','季节·天气·自然'),
    ('winter','冬天','noun','季节·天气·自然'),
    ('season','季节','noun','季节·天气·自然'),
    ('weather','天气','noun','季节·天气·自然'),
    ('rainy','下雨的','adj','季节·天气·自然'),
    ('sunny','晴朗的','adj','季节·天气·自然'),
    ('cloudy','多云的','adj','季节·天气·自然'),
    ('windy','有风的','adj','季节·天气·自然'),
    ('snowy','下雪的','adj','季节·天气·自然'),
    ('dry','干燥的','adj','季节·天气·自然'),
    ('wet','湿的','adj','季节·天气·自然'),
    ('field','田野','noun','季节·天气·自然'),
    ('hill','小山','noun','季节·天气·自然'),
    ('island','岛','noun','季节·天气·自然'),
    ('monday','星期一','noun','时间·星期'),
    ('tuesday','星期二','noun','时间·星期'),
    ('wednesday','星期三','noun','时间·星期'),
    ('thursday','星期四','noun','时间·星期'),
    ('friday','星期五','noun','时间·星期'),
    ('saturday','星期六','noun','时间·星期'),
    ('sunday','星期日','noun','时间·星期'),
    ('month','月份','noun','时间·星期'),
    ('hour','小时','noun','时间·星期'),
    ('minute','分钟','noun','时间·星期'),
    ('noon','中午','noun','时间·星期'),
    ('midnight','午夜','noun','时间·星期'),
    ('calendar','日历','noun','时间·星期'),
    ('headache','头痛','noun','身体·健康'),
    ('toothache','牙痛','noun','身体·健康'),
    ('cough','咳嗽','noun','身体·健康'),
    ('fever','发烧','noun','身体·健康'),
    ('wash','洗','verb','身体·健康'),
    ('brush','刷','verb','身体·健康'),
    ('comb','梳子','noun','身体·健康'),
    ('carry','搬运','verb','动词Ⅱ'),
    ('catch','接住','verb','动词Ⅱ'),
    ('climb','爬','verb','动词Ⅱ'),
    ('cook','烹饪','verb','动词Ⅱ'),
    ('cut','切','verb','动词Ⅱ'),
    ('dig','挖','verb','动词Ⅱ'),
    ('drop','掉落','verb','动词Ⅱ'),
    ('feed','喂养','verb','动词Ⅱ'),
    ('fill','装满','verb','动词Ⅱ'),
    ('fix','修理','verb','动词Ⅱ'),
    ('follow','跟随','verb','动词Ⅱ'),
    ('grow','生长','verb','动词Ⅱ'),
    ('hide','隐藏','verb','动词Ⅱ'),
    ('hit','打','verb','动词Ⅱ'),
    ('hold','拿着','verb','动词Ⅱ'),
    ('hurt','伤害','verb','动词Ⅱ'),
    ('kick','踢','verb','动词Ⅱ'),
    ('knock','敲','verb','动词Ⅱ'),
    ('lay','放置','verb','动词Ⅱ'),
    ('leave','离开','verb','动词Ⅱ'),
    ('lift','举起','verb','动词Ⅱ'),
    ('lock','锁','verb','动词Ⅱ'),
    ('mix','混合','verb','动词Ⅱ'),
    ('move','移动','verb','动词Ⅱ'),
    ('pass','通过/传递','verb','动词Ⅱ'),
    ('pick','挑选','verb','动词Ⅱ'),
    ('point','指','verb','动词Ⅱ'),
    ('pour','倒','verb','动词Ⅱ'),
    ('pull','拉','verb','动词Ⅱ'),
    ('push','推','verb','动词Ⅱ'),
    ('raise','举起','verb','动词Ⅱ'),
    ('reach','到达','verb','动词Ⅱ'),
    ('ride','骑','verb','动词Ⅱ'),
    ('roll','滚动','verb','动词Ⅱ'),
    ('save','节省','verb','动词Ⅱ'),
    ('share','分享','verb','动词Ⅱ'),
    ('shout','喊叫','verb','动词Ⅱ'),
    ('show','展示','verb','动词Ⅱ'),
    ('shake','摇晃','verb','动词Ⅱ'),
    ('smell','闻','verb','动词Ⅱ'),
    ('spend','花费','verb','动词Ⅱ'),
    ('spill','洒出','verb','动词Ⅱ'),
    ('stretch','伸展','verb','动词Ⅱ'),
    ('sweep','扫','verb','动词Ⅱ'),
    ('throw','扔','verb','动词Ⅱ'),
    ('tie','系','verb','动词Ⅱ'),
    ('touch','触摸','verb','动词Ⅱ'),
    ('turn','转','verb','动词Ⅱ'),
    ('use','使用','verb','动词Ⅱ'),
    ('visit','访问','verb','动词Ⅱ'),
    ('wait','等待','verb','动词Ⅱ'),
    ('wake','醒来','verb','动词Ⅱ'),
    ('wear','穿','verb','动词Ⅱ'),
    ('win','赢','verb','动词Ⅱ'),
    ('wish','希望','verb','动词Ⅱ'),
    ('wrap','包裹','verb','动词Ⅱ'),
    ('yell','大叫','verb','动词Ⅱ'),
    ('busy','忙碌的','adj','形容词Ⅱ'),
    ('careful','小心的','adj','形容词Ⅱ'),
    ('clever','聪明的','adj','形容词Ⅱ'),
    ('curious','好奇的','adj','形容词Ⅱ'),
    ('different','不同的','adj','形容词Ⅱ'),
    ('early','早的','adj','形容词Ⅱ'),
    ('excited','兴奋的','adj','形容词Ⅱ'),
    ('famous','著名的','adj','形容词Ⅱ'),
    ('fine','好的','adj','形容词Ⅱ'),
    ('friendly','友好的','adj','形容词Ⅱ'),
    ('funny','有趣的','adj','形容词Ⅱ'),
    ('gentle','温柔的','adj','形容词Ⅱ'),
    ('glad','高兴的','adj','形容词Ⅱ'),
    ('great','伟大的','adj','形容词Ⅱ'),
    ('healthy','健康的','adj','形容词Ⅱ'),
    ('honest','诚实的','adj','形容词Ⅱ'),
    ('important','重要的','adj','形容词Ⅱ'),
    ('interesting','有趣的','adj','形容词Ⅱ'),
    ('kind','善良的','adj','形容词Ⅱ'),
    ('large','大的','adj','形容词Ⅱ'),
    ('late','迟的','adj','形容词Ⅱ'),
    ('lazy','懒惰的','adj','形容词Ⅱ'),
    ('loud','大声的','adj','形容词Ⅱ'),
    ('lovely','可爱的','adj','形容词Ⅱ'),
    ('naughty','淘气的','adj','形容词Ⅱ'),
    ('nervous','紧张的','adj','形容词Ⅱ'),
    ('noisy','吵闹的','adj','形容词Ⅱ'),
    ('proud','自豪的','adj','形容词Ⅱ'),
    ('quick','快的','adj','形容词Ⅱ'),
    ('ready','准备好的','adj','形容词Ⅱ'),
    ('real','真的','adj','形容词Ⅱ'),
    ('rich','富有的','adj','形容词Ⅱ'),
    ('safe','安全的','adj','形容词Ⅱ'),
    ('shy','害羞的','adj','形容词Ⅱ'),
    ('silly','傻的','adj','形容词Ⅱ'),
    ('simple','简单的','adj','形容词Ⅱ'),
    ('special','特别的','adj','形容词Ⅱ'),
    ('strange','奇怪的','adj','形容词Ⅱ'),
    ('sure','确定的','adj','形容词Ⅱ'),
    ('surprised','惊讶的','adj','形容词Ⅱ'),
    ('terrible','可怕的','adj','形容词Ⅱ'),
    ('thick','厚的','adj','形容词Ⅱ'),
    ('tiny','微小的','adj','形容词Ⅱ'),
    ('true','真实的','adj','形容词Ⅱ'),
    ('useful','有用的','adj','形容词Ⅱ'),
    ('weak','弱的','adj','形容词Ⅱ'),
    ('wide','宽的','adj','形容词Ⅱ'),
    ('wonderful','精彩的','adj','形容词Ⅱ'),
    ('wrong','错误的','adj','形容词Ⅱ'),
    ('sport','运动','noun','运动·爱好'),
    ('game','游戏','noun','运动·爱好'),
    ('team','团队','noun','运动·爱好'),
    ('race','赛跑','noun','运动·爱好'),
    ('match','比赛','noun','运动·爱好'),
    ('score','得分','noun','运动·爱好'),
    ('goal','进球','noun','运动·爱好'),
    ('music','音乐','noun','运动·爱好'),
    ('song','歌曲','noun','运动·爱好'),
    ('drum','鼓','noun','运动·爱好'),
    ('guitar','吉他','noun','运动·爱好'),
    ('piano','钢琴','noun','运动·爱好'),
    ('violin','小提琴','noun','运动·爱好'),
    ('movie','电影','noun','运动·爱好'),
    ('story','故事','noun','运动·爱好'),
    ('myself','我自己','pron','代词·限定词Ⅱ'),
    ('yourself','你自己','pron','代词·限定词Ⅱ'),
    ('himself','他自己','pron','代词·限定词Ⅱ'),
    ('herself','她自己','pron','代词·限定词Ⅱ'),
    ('itself','它自己','pron','代词·限定词Ⅱ'),
    ('everyone','每个人','pron','代词·限定词Ⅱ'),
    ('everything','每件事','pron','代词·限定词Ⅱ'),
    ('nobody','没有人','pron','代词·限定词Ⅱ'),
    ('nothing','没有东西','pron','代词·限定词Ⅱ'),
    ('somebody','某人','pron','代词·限定词Ⅱ'),
    ('something','某物','pron','代词·限定词Ⅱ'),
    ('anybody','任何人','pron','代词·限定词Ⅱ'),
    ('anything','任何事物','pron','代词·限定词Ⅱ'),
    ('all','全部','art','代词·限定词Ⅱ'),
    ('both','两者都','art','代词·限定词Ⅱ'),
    ('each','每个','art','代词·限定词Ⅱ'),
    ('any','任何','art','代词·限定词Ⅱ'),
    ('many','许多','adj','代词·限定词Ⅱ'),
    ('much','许多','adj','代词·限定词Ⅱ'),
    ('more','更多','adj','代词·限定词Ⅱ'),
    ('most','最多','adj','代词·限定词Ⅱ'),
    ('few','很少','adj','代词·限定词Ⅱ'),
    ('little','少许','adj','代词·限定词Ⅱ'),
    ('enough','足够','adj','代词·限定词Ⅱ'),
    ('other','其他的','adj','代词·限定词Ⅱ'),
    ('after','在……之后','prep','介词·连词Ⅱ'),
    ('before','在……之前','prep','介词·连词Ⅱ'),
    ('since','自从','prep','介词·连词Ⅱ'),
    ('until','直到','prep','介词·连词Ⅱ'),
    ('while','当……时','conj','介词·连词Ⅱ'),
    ('during','在……期间','prep','介词·连词Ⅱ'),
    ('through','穿过','prep','介词·连词Ⅱ'),
    ('across','横穿','prep','介词·连词Ⅱ'),
    ('along','沿着','prep','介词·连词Ⅱ'),
    ('around','围绕','prep','介词·连词Ⅱ'),
    ('into','进入','prep','介词·连词Ⅱ'),
    ('onto','到……上','prep','介词·连词Ⅱ'),
    ('past','经过','prep','介词·连词Ⅱ'),
    ('toward','朝向','prep','介词·连词Ⅱ'),
    ('without','没有','prep','介词·连词Ⅱ'),
    ('against','反对','prep','介词·连词Ⅱ'),
    ('except','除了','prep','介词·连词Ⅱ'),
    ('among','在……之中','prep','介词·连词Ⅱ'),
    ('about','关于','prep','介词·连词Ⅱ'),
    ('above','在……上方','prep','介词·连词Ⅱ'),
    ('below','在……下方','prep','介词·连词Ⅱ'),
    ('when','什么时候','adv','疑问·副词'),
    ('which','哪一个','pron','疑问·副词'),
    ('whose','谁的','pron','疑问·副词'),
    ('already','已经','adv','疑问·副词'),
    ('usually','通常','adv','疑问·副词'),
    ('often','经常','adv','疑问·副词'),
    ('sometimes','有时','adv','疑问·副词'),
    ('never','从不','adv','疑问·副词'),
    ('ever','曾经','adv','疑问·副词'),
    ('just','刚刚','adv','疑问·副词'),
    ('still','仍然','adv','疑问·副词'),
    ('even','甚至','adv','疑问·副词'),
    ('only','仅仅','adv','疑问·副词'),
    ('really','真正地','adv','疑问·副词'),
    ('almost','几乎','adv','疑问·副词'),
    ('perhaps','或许','adv','疑问·副词'),
    ('maybe','可能','adv','疑问·副词'),
    ('quite','相当','adv','疑问·副词'),
    ('together','一起','adv','疑问·副词'),
    ('well','好','adv','疑问·副词'),
    ('soon','很快','adv','疑问·副词'),
    ('hundred','百','num','数词·量词'),
    ('thousand','千','num','数词·量词'),
    ('first','第一','adj','数词·量词'),
    ('second','第二','adj','数词·量词'),
    ('third','第三','adj','数词·量词'),
    ('once','一次','adv','数词·量词'),
    ('twice','两次','adv','数词·量词'),
    ('boy','男孩','noun','其他补充'),
    ('girl','女孩','noun','其他补充'),
    ('man','男人','noun','其他补充'),
    ('woman','女人','noun','其他补充'),
    ('child','孩子','noun','其他补充'),
    # 5-6年级
    ('idea','主意','noun','抽象概念'),
    ('plan','计划','noun','抽象概念'),
    ('dream','梦想','noun','抽象概念'),
    ('truth','真相','noun','抽象概念'),
    ('secret','秘密','noun','抽象概念'),
    ('memory','记忆','noun','抽象概念'),
    ('thought','想法','noun','抽象概念'),
    ('hope','希望','noun','抽象概念'),
    ('chance','机会','noun','抽象概念'),
    ('choice','选择','noun','抽象概念'),
    ('decision','决定','noun','抽象概念'),
    ('reason','原因','noun','抽象概念'),
    ('result','结果','noun','抽象概念'),
    ('example','例子','noun','抽象概念'),
    ('problem','问题','noun','抽象概念'),
    ('answer','答案','noun','抽象概念'),
    ('question','问题','noun','抽象概念'),
    ('information','信息','noun','抽象概念'),
    ('news','新闻','noun','抽象概念'),
    ('message','消息','noun','抽象概念'),
    ('rule','规则','noun','抽象概念'),
    ('map','地图','noun','抽象概念'),
    ('list','列表','noun','抽象概念'),
    ('address','地址','noun','抽象概念'),
    ('price','价格','noun','抽象概念'),
    ('size','尺寸','noun','抽象概念'),
    ('weight','重量','noun','抽象概念'),
    ('neighbor','邻居','noun','人与社会'),
    ('guest','客人','noun','人与社会'),
    ('host','主人','noun','人与社会'),
    ('member','成员','noun','人与社会'),
    ('group','小组','noun','人与社会'),
    ('community','社区','noun','人与社会'),
    ('country','国家','noun','人与社会'),
    ('world','世界','noun','人与社会'),
    ('people','人们','noun','人与社会'),
    ('person','人','noun','人与社会'),
    ('adult','成年人','noun','人与社会'),
    ('parent','父母','noun','人与社会'),
    ('relative','亲戚','noun','人与社会'),
    ('owner','主人','noun','人与社会'),
    ('leader','领导者','noun','人与社会'),
    ('player','运动员','noun','人与社会'),
    ('worker','工人','noun','人与社会'),
    ('farmer','农民','noun','人与社会'),
    ('driver','司机','noun','人与社会'),
    ('nurse','护士','noun','人与社会'),
    ('doctor','医生','noun','人与社会'),
    ('student','学生','noun','人与社会'),
    ('pupil','小学生','noun','人与社会'),
    ('earth','地球','noun','自然·环境'),
    ('space','太空','noun','自然·环境'),
    ('planet','行星','noun','自然·环境'),
    ('environment','环境','noun','自然·环境'),
    ('forest','森林','noun','自然·环境'),
    ('desert','沙漠','noun','自然·环境'),
    ('climate','气候','noun','自然·环境'),
    ('temperature','温度','noun','自然·环境'),
    ('power','力量/电力','noun','自然·环境'),
    ('shadow','影子','noun','自然·环境'),
    ('sound','声音','noun','自然·环境'),
    ('noise','噪音','noun','自然·环境'),
    ('voice','声音','noun','自然·环境'),
    ('taste','味道','noun','自然·环境'),
    ('lesson','课','noun','学校·学习'),
    ('class','班级','noun','学校·学习'),
    ('subject','科目','noun','学校·学习'),
    ('math','数学','noun','学校·学习'),
    ('science','科学','noun','学校·学习'),
    ('history','历史','noun','学校·学习'),
    ('geography','地理','noun','学校·学习'),
    ('language','语言','noun','学校·学习'),
    ('english','英语','noun','学校·学习'),
    ('exam','考试','noun','学校·学习'),
    ('test','测试','noun','学校·学习'),
    ('grade','成绩','noun','学校·学习'),
    ('homework','家庭作业','noun','学校·学习'),
    ('practice','练习','noun','学校·学习'),
    ('study','学习','verb','学校·学习'),
    ('learn','学习','verb','学校·学习'),
    ('teach','教','verb','学校·学习'),
    ('explain','解释','verb','学校·学习'),
    ('understand','理解','verb','学校·学习'),
    ('remember','记住','verb','学校·学习'),
    ('forget','忘记','verb','学校·学习'),
    ('prepare','准备','verb','学校·学习'),
    ('improve','提高','verb','学校·学习'),
    ('check','检查','verb','学校·学习'),
    ('correct','纠正','verb','学校·学习'),
    ('review','复习','verb','学校·学习'),
    ('accept','接受','verb','动词Ⅲ'),
    ('add','添加','verb','动词Ⅲ'),
    ('allow','允许','verb','动词Ⅲ'),
    ('appear','出现','verb','动词Ⅲ'),
    ('arrive','到达','verb','动词Ⅲ'),
    ('believe','相信','verb','动词Ⅲ'),
    ('borrow','借','verb','动词Ⅲ'),
    ('break','打破','verb','动词Ⅲ'),
    ('bring','带来','verb','动词Ⅲ'),
    ('build','建造','verb','动词Ⅲ'),
    ('buy','买','verb','动词Ⅲ'),
    ('celebrate','庆祝','verb','动词Ⅲ'),
    ('change','改变','verb','动词Ⅲ'),
    ('collect','收集','verb','动词Ⅲ'),
    ('compare','比较','verb','动词Ⅲ'),
    ('complete','完成','verb','动词Ⅲ'),
    ('connect','连接','verb','动词Ⅲ'),
    ('consider','考虑','verb','动词Ⅲ'),
    ('continue','继续','verb','动词Ⅲ'),
    ('control','控制','verb','动词Ⅲ'),
    ('copy','复制','verb','动词Ⅲ'),
    ('count','数','verb','动词Ⅲ'),
    ('cover','覆盖','verb','动词Ⅲ'),
    ('create','创造','verb','动词Ⅲ'),
    ('cross','穿过','verb','动词Ⅲ'),
    ('decide','决定','verb','动词Ⅲ'),
    ('deliver','递送','verb','动词Ⅲ'),
    ('describe','描述','verb','动词Ⅲ'),
    ('discover','发现','verb','动词Ⅲ'),
    ('divide','分开','verb','动词Ⅲ'),
    ('enjoy','享受','verb','动词Ⅲ'),
    ('enter','进入','verb','动词Ⅲ'),
    ('escape','逃跑','verb','动词Ⅲ'),
    ('explore','探索','verb','动词Ⅲ'),
    ('fail','失败','verb','动词Ⅲ'),
    ('finish','完成','verb','动词Ⅲ'),
    ('guess','猜测','verb','动词Ⅲ'),
    ('happen','发生','verb','动词Ⅲ'),
    ('imagine','想象','verb','动词Ⅲ'),
    ('include','包括','verb','动词Ⅲ'),
    ('increase','增加','verb','动词Ⅲ'),
    ('invent','发明','verb','动词Ⅲ'),
    ('invite','邀请','verb','动词Ⅲ'),
    ('join','加入','verb','动词Ⅲ'),
    ('judge','判断','verb','动词Ⅲ'),
    ('keep','保持','verb','动词Ⅲ'),
    ('lead','带领','verb','动词Ⅲ'),
    ('lend','借出','verb','动词Ⅲ'),
    ('manage','管理','verb','动词Ⅲ'),
    ('mean','意思','verb','动词Ⅲ'),
    ('meet','遇见','verb','动词Ⅲ'),
    ('mind','介意','verb','动词Ⅲ'),
    ('miss','想念','verb','动词Ⅲ'),
    ('notice','注意','verb','动词Ⅲ'),
    ('offer','提供','verb','动词Ⅲ'),
    ('own','拥有','verb','动词Ⅲ'),
    ('pack','打包','verb','动词Ⅲ'),
    ('perform','表演','verb','动词Ⅲ'),
    ('prefer','更喜欢','verb','动词Ⅲ'),
    ('prevent','防止','verb','动词Ⅲ'),
    ('produce','生产','verb','动词Ⅲ'),
    ('promise','承诺','verb','动词Ⅲ'),
    ('protect','保护','verb','动词Ⅲ'),
    ('prove','证明','verb','动词Ⅲ'),
    ('receive','收到','verb','动词Ⅲ'),
    ('refuse','拒绝','verb','动词Ⅲ'),
    ('relax','放松','verb','动词Ⅲ'),
    ('remind','提醒','verb','动词Ⅲ'),
    ('repeat','重复','verb','动词Ⅲ'),
    ('reply','回复','verb','动词Ⅲ'),
    ('report','报告','verb','动词Ⅲ'),
    ('return','返回','verb','动词Ⅲ'),
    ('search','搜索','verb','动词Ⅲ'),
    ('separate','分离','verb','动词Ⅲ'),
    ('serve','服务','verb','动词Ⅲ'),
    ('sign','签名','verb','动词Ⅲ'),
    ('solve','解决','verb','动词Ⅲ'),
    ('suggest','建议','verb','动词Ⅲ'),
    ('supply','供应','verb','动词Ⅲ'),
    ('support','支持','verb','动词Ⅲ'),
    ('suppose','假设','verb','动词Ⅲ'),
    ('thank','感谢','verb','动词Ⅲ'),
    ('train','训练','verb','动词Ⅲ'),
    ('travel','旅行','verb','动词Ⅲ'),
    ('treat','对待','verb','动词Ⅲ'),
    ('trust','信任','verb','动词Ⅲ'),
    ('try','尝试','verb','动词Ⅲ'),
    ('warn','警告','verb','动词Ⅲ'),
    ('worry','担心','verb','动词Ⅲ'),
    ('able','能够的','adj','形容词Ⅲ'),
    ('active','活跃的','adj','形容词Ⅲ'),
    ('amazing','惊人的','adj','形容词Ⅲ'),
    ('ancient','古老的','adj','形容词Ⅲ'),
    ('attractive','有吸引力的','adj','形容词Ⅲ'),
    ('available','可用的','adj','形容词Ⅲ'),
    ('basic','基本的','adj','形容词Ⅲ'),
    ('boring','无聊的','adj','形容词Ⅲ'),
    ('certain','确定的','adj','形容词Ⅲ'),
    ('comfortable','舒适的','adj','形容词Ⅲ'),
    ('common','共同的','adj','形容词Ⅲ'),
    ('confident','自信的','adj','形容词Ⅲ'),
    ('convenient','方便的','adj','形容词Ⅲ'),
    ('correct','正确的','adj','形容词Ⅲ'),
    ('dangerous','危险的','adj','形容词Ⅲ'),
    ('deep','深的','adj','形容词Ⅲ'),
    ('difficult','困难的','adj','形容词Ⅲ'),
    ('disappointed','失望的','adj','形容词Ⅲ'),
    ('empty','空的','adj','形容词Ⅲ'),
    ('excellent','优秀的','adj','形容词Ⅲ'),
    ('expensive','昂贵的','adj','形容词Ⅲ'),
    ('favorite','最喜欢的','adj','形容词Ⅲ'),
    ('female','女性的','adj','形容词Ⅲ'),
    ('foreign','外国的','adj','形容词Ⅲ'),
    ('free','自由的/免费的','adj','形容词Ⅲ'),
    ('fresh','新鲜的','adj','形容词Ⅲ'),
    ('full','满的','adj','形容词Ⅲ'),
    ('generous','慷慨的','adj','形容词Ⅲ'),
    ('handsome','英俊的','adj','形容词Ⅲ'),
    ('helpful','有帮助的','adj','形容词Ⅲ'),
    ('huge','巨大的','adj','形容词Ⅲ'),
    ('independent','独立的','adj','形容词Ⅲ'),
    ('intelligent','聪明的','adj','形容词Ⅲ'),
    ('likely','可能的','adj','形容词Ⅲ'),
    ('local','当地的','adj','形容词Ⅲ'),
    ('lucky','幸运的','adj','形容词Ⅲ'),
    ('modern','现代的','adj','形容词Ⅲ'),
    ('natural','自然的','adj','形容词Ⅲ'),
    ('necessary','必要的','adj','形容词Ⅲ'),
    ('normal','正常的','adj','形容词Ⅲ'),
    ('obvious','明显的','adj','形容词Ⅲ'),
    ('opposite','相反的','adj','形容词Ⅲ'),
    ('ordinary','普通的','adj','形容词Ⅲ'),
    ('painful','痛苦的','adj','形容词Ⅲ'),
    ('perfect','完美的','adj','形容词Ⅲ'),
    ('personal','个人的','adj','形容词Ⅲ'),
    ('physical','身体的','adj','形容词Ⅲ'),
    ('pleasant','愉快的','adj','形容词Ⅲ'),
    ('polite','礼貌的','adj','形容词Ⅲ'),
    ('popular','流行的','adj','形容词Ⅲ'),
    ('positive','积极的','adj','形容词Ⅲ'),
    ('possible','可能的','adj','形容词Ⅲ'),
    ('potential','潜在的','adj','形容词Ⅲ'),
    ('powerful','强大的','adj','形容词Ⅲ'),
    ('precious','珍贵的','adj','形容词Ⅲ'),
    ('proper','恰当的','adj','形容词Ⅲ'),
    ('public','公共的','adj','形容词Ⅲ'),
    ('recent','最近的','adj','形容词Ⅲ'),
    ('regular','有规律的','adj','形容词Ⅲ'),
    ('responsible','负责的','adj','形容词Ⅲ'),
    ('sensitive','敏感的','adj','形容词Ⅲ'),
    ('serious','严肃的','adj','形容词Ⅲ'),
    ('sharp','锋利的','adj','形容词Ⅲ'),
    ('significant','重要的','adj','形容词Ⅲ'),
    ('silent','沉默的','adj','形容词Ⅲ'),
    ('similar','相似的','adj','形容词Ⅲ'),
    ('smooth','光滑的','adj','形容词Ⅲ'),
    ('social','社交的','adj','形容词Ⅲ'),
    ('solid','坚固的','adj','形容词Ⅲ'),
    ('specific','具体的','adj','形容词Ⅲ'),
    ('standard','标准的','adj','形容词Ⅲ'),
    ('straight','直的','adj','形容词Ⅲ'),
    ('strict','严格的','adj','形容词Ⅲ'),
    ('suitable','合适的','adj','形容词Ⅲ'),
    ('surprised','惊讶的','adj','形容词Ⅲ'),
    ('talented','有才能的','adj','形容词Ⅲ'),
    ('technical','技术的','adj','形容词Ⅲ'),
    ('temporary','暂时的','adj','形容词Ⅲ'),
    ('terrific','极好的','adj','形容词Ⅲ'),
    ('tight','紧的','adj','形容词Ⅲ'),
    ('tough','坚韧的','adj','形容词Ⅲ'),
    ('traditional','传统的','adj','形容词Ⅲ'),
    ('typical','典型的','adj','形容词Ⅲ'),
    ('unique','独特的','adj','形容词Ⅲ'),
    ('valuable','有价值的','adj','形容词Ⅲ'),
    ('various','各种各样的','adj','形容词Ⅲ'),
    ('violent','暴力的','adj','形容词Ⅲ'),
    ('visible','可见的','adj','形容词Ⅲ'),
    ('wealthy','富有的','adj','形容词Ⅲ'),
    ('wild','野生的','adj','形容词Ⅲ'),
    ('wise','明智的','adj','形容词Ⅲ'),
    ('christmas','圣诞节','noun','节日·文化'),
    ('easter','复活节','noun','节日·文化'),
    ('halloween','万圣节','noun','节日·文化'),
    ('lantern','灯笼','noun','节日·文化'),
    ('firework','烟花','noun','节日·文化'),
    ('dragon','龙','noun','节日·文化'),
    ('culture','文化','noun','节日·文化'),
    ('tradition','传统','noun','节日·文化'),
    ('custom','习俗','noun','节日·文化'),
    ('holiday','假日','noun','节日·文化'),
    ('celebrate','庆祝','verb','节日·文化'),
    ('decorate','装饰','verb','节日·文化'),
    ('computer','电脑','noun','科技·媒体'),
    ('internet','互联网','noun','科技·媒体'),
    ('website','网站','noun','科技·媒体'),
    ('email','电子邮件','noun','科技·媒体'),
    ('screen','屏幕','noun','科技·媒体'),
    ('keyboard','键盘','noun','科技·媒体'),
    ('mouse','鼠标','noun','科技·媒体'),
    ('video','视频','noun','科技·媒体'),
    ('photo','照片','noun','科技·媒体'),
    ('camera','相机','noun','科技·媒体'),
    ('digital','数字的','adj','科技·媒体'),
    ('online','在线的','adj','科技·媒体'),
    ('robot','机器人','noun','科技·媒体'),
    ('rarely','很少','adv','时间·频率副词'),
    ('frequently','频繁地','adv','时间·频率副词'),
    ('occasionally','偶尔','adv','时间·频率副词'),
    ('immediately','立即','adv','时间·频率副词'),
    ('suddenly','突然','adv','时间·频率副词'),
    ('quickly','快速地','adv','时间·频率副词'),
    ('slowly','缓慢地','adv','时间·频率副词'),
    ('carefully','小心地','adv','时间·频率副词'),
    ('easily','容易地','adv','时间·频率副词'),
    ('happily','快乐地','adv','时间·频率副词'),
    ('finally','最终','adv','时间·频率副词'),
    ('recently','最近','adv','时间·频率副词'),
    ('although','虽然','conj','连词·介词·情态'),
    ('though','虽然','conj','连词·介词·情态'),
    ('unless','除非','conj','连词·介词·情态'),
    ('whether','是否','conj','连词·介词·情态'),
    ('should','应该','aux','连词·介词·情态'),
    ('would','会','aux','连词·介词·情态'),
    ('could','可以','aux','连词·介词·情态'),
    ('must','必须','aux','连词·介词·情态'),
    ('may','可能','aux','连词·介词·情态'),
    ('might','也许','aux','连词·介词·情态'),
    ('neither','两者都不','adj','连词·介词·情态'),
    ('nor','也不','conj','连词·介词·情态'),
    ('if','如果','conj','连词·介词·情态'),
    ('than','比','conj','连词·介词·情态'),
]

# ============================================================
# 构建词表
# ============================================================
result_words = []
seen = set()

def make_entry(word, cn, pos, category_cn):
    wl = word.lower()
    if wl in seen:
        return None
    seen.add(wl)

    if wl in OLD_MAP:
        old = OLD_MAP[wl]
        elem = old['element']
        sentence = old.get('sentence', '')
        if not sentence:
            sentence = make_sentence(word, cn, pos)
    else:
        elem = assign_element(word)
        sentence = make_sentence(word, cn, pos)

    return {
        'word': word,
        'cn': cn,
        'pos': pos,
        'category_cn': category_cn,
        'element': elem,
        'sentence': sentence,
        'tier': TIER_MAP.get(category_cn, 'intermediate')
    }

# Step 1: 先从旧词库映射已有词
for w in OLD['words']:
    wl = w['word'].lower()
    old_cat = w.get('category_cn', '其他')
    new_cat = CAT_MAP.get(old_cat, '其他补充')
    entry = make_entry(w['word'], w['cn'], w['pos'], new_cat)
    if entry:
        result_words.append(entry)

# Step 2: 再加新词（不存在的才加）
for nw in NEW_WORDS:
    entry = make_entry(*nw)
    if entry:
        result_words.append(entry)

# ============================================================
# 输出报告
# ============================================================
by_tier = {}
by_cat = {}
elem_count = {}
for w in result_words:
    by_tier[w['tier']] = by_tier.get(w['tier'], 0) + 1
    by_cat[w['category_cn']] = by_cat.get(w['category_cn'], 0) + 1
    elem_count[w['element']] = elem_count.get(w['element'], 0) + 1

print(f'五行英语牌 — 词表生成报告 v2.0')
print(f'=' * 50)
print(f'总词数: {len(result_words)}')
print(f'初级(beginner): {by_tier.get("beginner",0)}')
print(f'中级(intermediate): {by_tier.get("intermediate",0)}')
print(f'\n五行分布:')
for e in ELEMENTS:
    print(f'  {e}: {elem_count.get(e,0)}')
print(f'\n主题分布:')
for cat, count in sorted(by_cat.items(), key=lambda x: -x[1]):
    print(f'  {cat}: {count}词')

# ============================================================
# 写入文件
# ============================================================
output = {
    'name': '五行英语牌词汇库',
    'version': '3.0',
    'description': '合并词库 v3，包含 beginner 和 intermediate 两个等级，按主题分类',
    'total_words': len(result_words),
    'words': result_words
}

with open('vocabulary.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f'\n✅ vocabulary.json 已生成！')
